# Generated by Django 5.2 on 2025-05-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=20, unique=True)),
                ('available_quantity', models.PositiveIntegerField()),
                ('unit_of_measure', models.CharField(default='grams', max_length=30)),
            ],
        ),
    ]
