# Generated by Django 5.2 on 2025-05-01 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_stockitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestForeCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef_name', models.CharField(max_length=100)),
                ('chef_id', models.CharField(max_length=50)),
                ('number_of_guests', models.PositiveIntegerField()),
                ('forecasted_quantity', models.PositiveIntegerField(help_text='Auto-calculated: guests * portion size')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.meal')),
            ],
        ),
    ]
