# Generated by Django 5.2 on 2025-05-01 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_guestforecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef_name', models.CharField(max_length=100)),
                ('order_datetime', models.DateTimeField(auto_now_add=True)),
                ('quantity_requested', models.PositiveIntegerField(help_text='Quantity requested in grams or units')),
                ('fulfilled', models.BooleanField(default=False)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.meal')),
            ],
        ),
    ]
