# Generated by Django 5.2 on 2025-05-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_stockorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity_before', models.PositiveIntegerField()),
                ('quantity_issued', models.PositiveIntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('issued_by', models.CharField(max_length=100)),
            ],
        ),
    ]
