# Generated by Django 5.2 on 2025-05-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='portion_size_grams',
        ),
        migrations.AddField(
            model_name='meal',
            name='portion_size',
            field=models.PositiveIntegerField(default=100, help_text='Portion size per guest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='unit_of_measure',
            field=models.CharField(default='grams', max_length=20),
        ),
    ]
