# Generated by Django 5.2 on 2025-05-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_remove_meal_portion_size_grams_meal_portion_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='cost_per_portion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='meal',
            name='portion_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='unit_of_measure',
            field=models.CharField(default='g', max_length=20),
        ),
    ]
