# Generated by Django 5.2 on 2025-05-04 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_meal_cost_per_portion_alter_meal_portion_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestforecast',
            name='shift',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('night', 'Night Shift')], default='lunch', max_length=20),
        ),
        migrations.AddField(
            model_name='guestforecast',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ForecastIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_person', models.FloatField()),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='system.guestforecast')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.stockitem')),
            ],
        ),
    ]
