# Generated by Django 5.2 on 2025-05-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_guestforecast_shift_guestforecast_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='unit_of_measure',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='unit_of_measurement',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('pcs', 'Pieces'), ('ltr', 'Liters'), ('g', 'Grams')], default='pcs', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='available_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='product_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
