# Generated by Django 5.2 on 2025-05-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='cost_per_portion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
